version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/weather_app

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: yarn

      - run:
          name: Build app
          command: yarn build

      - run: yarn test

      - deploy:
          name: Deploy to S3 if tests pass and branch is Master
          command: |
            if [ "${CIRCLE_BRANCH}" != "master" ] ; then
              echo "not in master"
              exit
            fi

            curl --silent --show-error --retry 5 https://bootstrap.pypa.io/get-pip.py | sudo python
            sudo apt-get install python-dev
            sudo pip install awscli

            aws --region us-west-2 s3 sync build weatherapp.lalilo.com
